const cnLanguage = {
    lang: "zh",
    regex: {
        noPassword: "至少包含一个数字一个字母,且长度在6-20之间",
        isRequired: "是必须输入的",
        short: "长度过短",
        long: "长度过长",
        noPhone: "应该是正常的电话号码",
        noNumber: "应该是一个数",
        noWholeNumber: "应该是一个数",
        small: "小于最小值",
        large: "大于最大值",
        noCPhone: "不是中国手机",
        noNPhone: "不是新西兰手机",
        noUPhone: "不是美国手机",
    },
    message: {
        PullToRefresh: "下拉刷新",
        PayInDiscount: "当面支付优惠",
        Search: "搜索",
        Beauty: "美容理发",
        Service: "生活服务",
        Trips: "旅游生活",
        Sport: "全民运动",
        Entertainment: "娱乐休闲",
        Food: "美食",
        Medicines: "保健药品",
        More: "全部分类",
        Money: "现金红包",
        Photos: "婚纱摄影",
        Sweet: "甜点",
        InputStore: "请输入商家名",
        Bottom: "已经到底了",
        IsLoading: "正在加载...",
        NoReview: "没有评价",
        NoBookmarks: "没有收藏",
        NoCoupon: "没有优惠券",
        Scan:"扫二维码"

    },
    sort: {
        SortDefault: "综合排序",
        SortSales: "销量最高",
        SortDistance: "距离最近",
        SortScore: "评分最高",
    },
    title: {
        Order: "订单",
        MyOrder: "我的订单",
        Home: "我的",
        Store: "首页"

    },
    store: {
        TotalPrice: "消费金额",
        DisPay: "店铺优惠",
        ActuallyPay: "需要支付",
        NoComments: "没有用户评价",
        Business: "营业天数",
        OpenTime: "营业时间",
        Phone: "店铺电话",
        Sales: "总售",
        Bulletin: "商家公告",
        Address: "店铺地址",
        CommentScore: "综合评分",
        Photos: "店铺照片",
        Reply: "回评",
        Description: "描述",
        MoreComments: "更多评论",
        PayInStore: "到店支付",
        DisPayIn: "到店支付享受折扣",
        Off: "优惠",
        Pay: "买单",
        Buy: "抢购",
        PayCheap: "团购套餐",
        DiscountInfo: "优惠信息",
        UserComments: "用户评价",
        StoreInfo: "商家信息",
        CommentNumber: "评价数",
        PayIn: "当面支付",
        Comment: "评价",
        Store: "商家",
        specialOffer: "优惠活动",
        Total: "团购销量",
        Checkout: "去结算",
        ClearCart: "清空购物车",
        StoreScore: "商家评分",
    },
    cart: {
        Cart: "购物车",
        Edit: "编辑",
        Cancel: "取消",
        Nothing: "购物车空空如也",
        Goto: "去逛逛",
        Delete: "删除"
    },
    order: {
        UnComment: "未评价",
        Confirm: "确认",
        Cancel: "取消",
        ClickHint: "点击确认,24小时后查看钱包.",
        Refunded: "已退款",
        AskingFor: "询问服务员后输入",
        CommentSuccessfully: "评论成功",
        Deploy: "发布",
        OrderInfo: "订单信息",
        StoreInfo: "商家信息",
        Detail: "详情",
        OrderId: "订单编号",
        OrderDate: "订单日期",
        Unused: "未使用",
        All: "全部",
        Refund: "退款",
        Finished: "已完成",
        PayFinished: "已支付",
        WaitingToActivate: "待激活",
        Waiting: "待处理",
        GoComment: "去评价",
        Active: "激活订单",
        WaitComment: "待评价",
        Nothing: "还没有订单",
        PayInStore: "当面支付",
        OrderFinished: "订单已完成",
        Continue: "再来一单",
        PleaseComment: "请为我们评价",
        Total: "实付",
        AtLeast: "至少输入两个字",
        Submit: "提交",
        MakeOrder: "提交订单",
        Subtotal: "小计",
        AllTotal: "合计",
        ShouldPay: "应付",
        ActuallyPay: "实付",
        Discount: "已优惠",
        PleaseShould: "请输入应付金额"
    },
    homeList: {
        MyOrder:"我的订单",
        Instruction:"指南",
        Coupons: "红包/卡券",
        MyCollections: "收藏",
        MyComments: "评价",
        Activity: "消息/活动",
        MyFriends: "邀请好友",
        About: "关于",
        CustomerService: "服务中心",
        BusinessJoin: "商家加盟",
        CustomerServiceNumber: "服务电话",
        WechatService: "公众号",
        NoMessage: "没有消息",
        Listen:"用户协议"
    }, pay: {
        MyWallet: "我的钱包",
        UseWallet: "使用钱包",
        UseWalletPay: "使用钱包支付",
        PayOrder: "支付订单",
        PayOver: "支付超市",
        PaymentTime: "支付剩余时间",
        Alipay: " 支付宝",
        Wechat: " 微信",
        Scan: "扫码",
        Confirm: "确认支付",
        AlipayApp: "支付宝App",
        WechatApp: "微信App",
    }, orderDetail: {
        Failed: "获取订单失败",
        ActuallyPay: "实付",
        Title: "订单详情",
        Finished: "订单完成",
        Thank: "感谢您对拼凑APP的支持,欢迎再次光临",
        BuyAgain: "再来一单",
        Contact: "联系商家",
        OrderId: "订单号码",
        OrderTime: "订单时间",
        PaymentMethod: "支付方式",
        Online: "在线支付",
        Cancel: "订单已取消",
    },
    alert: {
        pleaseWaiting: "请稍等，订单确认中...",
        deleteSuccessfully: "删除成功",
        deleteFailed: "删除失败",
        delete: "删除",
        payFinished: "支付已完成",
        payNotFinished: "未完成",
        WarmPrompt: "温馨提示",
        NoWechat: '没有安装微信软件，请您安装微信之后再试',
        OverTime: "订单支付超时，请重新下单",
        PleaseLogin: "请先登录",
        walletPay: "代金券支付成功",
        PaySuccess: "支付成功",
        PayFailed: "支付失败",
        isRefund: "订单已退款",
        isActivated: "订单已激活",
        Error: "出错了,请刷新",
        TooLess: "当面支付不得少于$1",
        CannotFind: "找不到商家",
        Failed: "提交失败,请重试",
        Disconnect: "失去连接,请刷新页面",
        Alipay: '请支付宝扫码或截图扫码',
        Wechat: '请用微信扫码或截图扫码',
        Paid: "该订单已完成支付",
        PhoneNumber: "请正确输入手机号码",
        VerifySent: "验证码已发送",
        VerifyFailed: "验证码发送失败",
        PasswordEmpty: "请输入密码或验证码",
        NoPassword: "请输入密码验证码",
        VerifyWrong: "验证码错误",
        VerifyExpired: "验证码已过期",
        RegisterFailed: "用户注册失败,请重试",
        PasswordWrong: "密码或验证码错误",
        LoginFailed: "用户登录失败",
        Disabled: "用户已被禁用",
        NoUser: "手机号未注册",
        PasswordChanged: "密码修改成功"
    }, home: {
        HomePage: "个人主页",
        Welcome: "欢迎登陆拼凑",
        Birthday: "生日",
        BirthdayIsChanged: "生日修改成功",
        BirthdayChangedFailed: "生日修改失败",
        Change: "修改",
        PleaseEnter: "请输入",
        BindingPhone: "绑定手机",
        ChangePassword: "修改密码",
        ShouldSame: "新密码必须和确认密码相同",
        ChangeSuccessfully: "密码修改成功",
        ChangeFailed: "密码修改失败",
        WrongOld: "修改失败,旧密码不正确",
        AboutPaycheap: "关于拼凑",
        Wallet: "钱包",
        Profile: "个人信息",
        Setting: "设置",
        Avatar: "头像",
        Hint: "小贴士: 新用户无需注册，直接输入账号密码则自动设为成功，输入手机号获取验证码后即可开始使用.",
        VerifyCode: "验证码",
        LoginRegister: "直接登陆",
        NewPassword: "新密码",
        OldPassword: "旧密码",
        ConfirmPassword: "确认密码",
        ForgetPassword: "忘记密码",
        LogOut: "退出",
        LogOutAccount: '退出账号',
        Home: "我的",
        Login: "登录",
        Register: "注册",
        Account: "账户",
        Phone: "手机",
        Password: "密码",
        Verify: "验证码",
        GetVerify: "获取验证码",
        HaveAccount: "以后账户, 去登录.",
        NoAccount: "没有账户去注册.",
        PleaseAccount: "请输入账户名",
        PleasePassword: "请输入密码",
        PleasePhone: "请输入手机号",
        PleaseVerify: "请输入验证码",
        NoLogin: "您还没有登录,请登录",
        ChangeAvatar: "更换头像",
        NickName: "昵称",
        NickNameIsChanged: "昵称已修改",
        EnterNickName: "请输入昵称",
        ConfirmChange: "确认更改",
    },
    product: {
        Details: "详情",
        StockNumber: "库存",
        Description: "商品描述",
        Score: "评分",
        Reminder: "温馨提示",
        Business: "营业天数",
        OpenTime: "营业时间",
        AvailableDate: "可用日期",
        Policy: "政策",
        Rules: "规则",
        Comments: "用户评价",
        Total: "总计",
        BuyNow: "立刻抢购",
    },
}


export default cnLanguage