const enLanguage = {
    lang: "en",
    regex: {
        noCPhone: " is not Chinese Number",
        noNPhone: " is not New Zealand Number",
        noUPhone: " is not USA Number",
        noPassword: " must contain one letter and one number and be between 6-20 characters",
        isRequired: " is Required field",
        short: "  is too Short",
        long: "   is too Long",
        noPhone: " should be correct Phone Number",
        noNumber: " should be Number",
        noWholeNumber: " should be Number",
        small: " is too Small",
        large: " is too Large",
    },
    product: {
        BuyNow: "Buy Now",
        Business: "Business Days",
        OpenTime: "Open Time",
        Details: "Details",
        StockNumber: "Available Number",
        Description: "Description",
        Score: "Score",
        Reminder: "Reminder",
        AvailableDate: "Available Date",
        Policy: "Policy",
        Rules: "Rules",
        Comments: "Comments",
        Total: "Total",
    },
    home: {

        HomePage: "Home Page",
        Welcome: "Login PayCheap",
        Change: "Change ",
        Birthday: "Birthday",
        BirthdayIsChanged: "Birthday Is Changed",
        BirthdayChangedFailed: "Birthday Changed Failed",
        WrongOld: "The Old Password is not correct",
        ShouldSame: "New Password should be same as Confirm Password",
        ChangeSuccessfully: "The Password is Changed Successfully",
        ChangeFailed: "The Password Change is Failed",
        ChangePassword: "Change Password",
        BindingPhone: "Binding Phone",
        AboutPaycheap: "About Us",
        Hint: "Hint for New User: Enter Phone Number and Get Verify Code, then enter verify code and set password for register.",
        Setting: "Setting",
        Profile: "Profile",
        Avatar: "Avatar",
        ChangeAvatar: "Change Avatar",
        NickName: "Nick Name",
        NickNameIsChanged: "NickName Is Changed",
        EnterNickName: "Please Enter Nick Name",
        ConfirmChange: " Confirm Change",
        LoginRegister: "Go Login",
        LogOut: "LogOut",
        LogOutAccount: 'Logout',
        Home: "Home",
        Wallet: "Wallet",
        NewPassword: "New Password",
        OldPassword: "Old Password",
        ConfirmPassword: "Confirm Password",
        PleaseEnter: "Enter ",
        ForgetPassword: "Forget Password",
        Login: "Login",
        Register: "Register",
        Account: "Account",
        Phone: "Phone",
        Password: "Password",
        Verify: "Verify",
        VerifyCode: "Verify Code",
        GetVerify: "Get Verify",
        HaveAccount: "Have Account. Go Login.",
        NoAccount: "No Account. Go Register.",
        PleaseAccount: "Please enter account",
        PleasePassword: "Enter Password",
        PleasePhone: "Enter Phone Number",
        PleaseVerify: "Enter Verify",
        NoLogin: "Please Login to check your orders",
    },
    alert: {
        pleaseWaiting: "Please waiting for the Order checking.",
        deleteSuccessfully: "Delete Successfully",
        deleteFailed: "Delete Failed",
        delete: "Delete",
        payFinished: "Paid",
        payNotFinished: "No Pay",
        WarmPrompt: "Warm Prompt",
        PaySuccess: "Pay Successfully",
        PayFailed: "Pay Failed",
        NoWechat: 'Please Install Wechat First',
        OverTime: "The Order is overtime. Please Make order again.",
        PleaseLogin: "Please Login",
        walletPay: "Successfully Paid by Coupons or Wallet!",
        isRefund: "The order is Refund",
        isActivated: "The order is Activated",
        Error: "Something went wrong",
        CannotFind: "Cannot Find Store",
        Failed: "Submit Failed. Try Again",
        Disconnect: "Disconnect. Please Refresh.",
        Alipay: 'Please scan or save image by Alipay',
        Wechat: 'Please scan or save image by Wechat',
        Paid: "The order has been paid",
        PhoneNumber: "Please enter correct Phone number",
        VerifySent: "The verification is sent",
        VerifyFailed: "Failed to send verification",
        PasswordEmpty: "Please enter the password or verify",
        NoPassword: "Password, Verify are required",
        VerifyWrong: "Wrong Verification",
        VerifyExpired: "Verification is expired",
        RegisterFailed: "Failed to Register",
        PasswordWrong: "Wrong Password or verify",
        LoginFailed: "Failed to Login",
        Disabled: "User is disabled",
        NoUser: "The Phone Number is not registered",
        PasswordChanged: "Password Changed Successfully",
        TooLess: "Total Price should not Less than $1"
    },
    orderDetail: {
        Failed: "Get Order Failed",
        Cancel: "Order Cancelled",
        ActuallyPay: "Pay",
        Title: "Order Detail",
        Finished: "Order Completed",
        Thank: "Thank you for the support to pay-cheap APP.",
        BuyAgain: "Go Shopping",
        Contact: "Contact Store",
        OrderId: "Order Number",
        OrderTime: "Order Time",
        PaymentMethod: "Payment Method",
        Online: "Pay Online",
    },
    pay: {
        MyWallet: "My Wallet",
        UseWallet: "Use Wallet",
        UseWalletPay: "Use my wallet to pay",
        PayOrder: "Pay Order",
        PayOver: "Over Time",
        PaymentTime: "Payment remaining time",
        Alipay: " Alipay",
        Wechat: " Wechat",
        AlipayApp: "Alipay App",
        WechatApp: "Wechat App",
        Scan: "Scan",
        Confirm: "Confirm Payment",
    },
    message: {
        PullToRefresh: "Pull to Refresh",
        PayInDiscount: "Pay Discount",
        Service: "Service",
        Trips: "Trips",
        Sport: "Sport",
        Search: "Search",
        Beauty: "Beauty",
        Entertainment: "Fun",
        Food: "Food",
        Medicines: "Medicines",
        More: "More",
        Money: "Money",
        Photos: "Photos",
        Sweet: "Sweet",
        InputStore: "Enter Store Name",
        Bottom: "No more data",
        IsLoading: "Loading...",
        NoReview: "No available review",
        NoBookmarks: "You don't have bookmarks",
        NoCoupon: "No avalaible coupon",
        Scan: "Scan QR Code"
    },
    sort: {
        SortDefault: "Default Sort",
        SortSales: "Sales Sort",
        SortDistance: "Distance Sort",
        SortScore: "Score Sort",
    },
    title: {
        MyOrder: "My Order",
        Order: "Order",
        Home: "Home",
        Store: "Store"
    },
    store: {
        Off: "OFF",
        NoComments: "No User Comments",
        Business: "Business Days",
        CommentScore: "Comment Score",
        Photos: "Store Photos",
        Address: "Address",
        Phone: "Phone",
        OpenTime: "Open Time",
        Bulletin: "Bulletin Board",
        Sales: "Sales",
        Total: "Totally Sales",
        MoreComments: "More Comments",
        Description: "Details",
        DisPayIn: "Discount to Pay",
        PayInStore: "Pay In Store",
        Pay: "Pay",
        Buy: "Buy",
        PayCheap: "Pay Cheap",
        TotalPrice: "Total Price",
        DisPay: "Discount",
        ActuallyPay: "Need to Pay",
        DiscountInfo: "Discount",
        UserComments: "Comments",
        StoreInfo: "Details",
        Reply: "Reply",
        CommentNumber: "Comments",
        PayIn: "Pay Now",
        Comment: "Comment",
        Store: "Store",
        specialOffer: "Special Offers",
        Checkout: "Check Out",
        ClearCart: "Clear Cart",
        StoreScore: "Store Score",
    },
    cart: {
        Cart: "Cart",
        Edit: "Edit",
        Cancel: "Cancel",
        Nothing: "Nothing in your shopping cart",
        Goto: "Go shopping",
        Delete: "Delete"
    },
    order: {
        Confirm: "Confirm",
        Cancel: "Cancel",
        UnComment: "Uncomment",
        ClickHint: "Confirm and check wallet after 24 hours.",
        Refunded: "Refunded",
        Finished: "Finished",
        AskingFor: "Asking Store for Price",
        OrderInfo: "Order Info",
        StoreInfo: "Store Info",
        Detail: "Detail",
        CommentSuccessfully: " Comment Successfully",
        Deploy: "Submit",
        OrderId: "Order Id",
        OrderDate: "Order Date",
        Unused: "Unused",
        All: "All",
        Refund: "Refund",
        PayFinished: "Paid",
        OrderFinished: "Order Finished",
        WaitComment: "Comment",
        Active: "Active",
        WaitingToActivate: "Activate",
        Waiting: "Waiting",
        GoComment: "Comment",
        Nothing: "You have no order",
        PayInStore: "Pay in store",
        Continue: "Continue",
        PleaseComment: "Please comment for us",
        Total: "You paid",
        AtLeast: "At least 2 words",
        Submit: "Submit",
        MakeOrder: "Make Order",
        Subtotal: "Subtotal",
        AllTotal: "Total",
        ShouldPay: "Amount ",
        ActuallyPay: "Pay",
        Discount: "Discount",
        PleaseShould: "Please enter the amount "
    },

    homeList: {
        MyOrder: "My Order",
        Instruction: "Instruction",
        Listen: "Listen",
        Coupons: "My Coupons",
        MyCollections: "Bookmarks",
        MyComments: "My Comments",
        Activity: "Activity",
        MyFriends: "Invite Friends",
        About: "About Us",
        CustomerService: "Customer Service",
        BusinessJoin: "Business Join",
        CustomerServiceNumber: "Service Number",
        WechatService: "Wetchat Service",
        NoMessage: "No avalaible message"
    },

}

export default enLanguage;